build.gradle, src/main/resources/application.properties
=> feat: add mongoDB dependency

src/main/java/com/example/emptySaver/controller/TimeTableController.java, src/main/java/com/example/emptySaver/domain/dto/TimeTableDto.java, src/main/java/com/example/emptySaver/domain/entity/Member.java, src/main/java/com/example/emptySaver/domain/entity/Schedule.java, src/main/java/com/example/emptySaver/domain/entity/Time_Table.java, src/main/java/com/example/emptySaver/service/MemberService.java, src/main/java/com/example/emptySaver/service/TimeTableService.java, src/main/java/com/example/emptySaver/utils/TimeDataToBitConverter.java, src/main/resources/application.yml, src/test/java/com/example/emptySaver/repository/DepartmentRepositoryTest.java, src/test/java/com/example/emptySaver/repository/ScheduleRepositoryTest.java, src/test/java/com/example/emptySaver/repository/SubjectRepositoryTest.java, src/test/java/com/example/emptySaver/repository/TimeTableRepositoryTest.java, src/test/java/com/example/emptySaver/service/TimeTableServiceTest.java
- timeTable관련 Controller 구현 완료
=> Table dev_ feat controller 

src/main/java/com/example/emptySaver/controller/TimeTableController.java, src/main/java/com/example/emptySaver/domain/dto/SubjectDto.java, src/main/java/com/example/emptySaver/domain/dto/TimeTableDto.java, src/main/java/com/example/emptySaver/domain/entity/Subject.java, src/main/java/com/example/emptySaver/repository/SubjectRepository.java, src/main/java/com/example/emptySaver/service/SubjectService.java, src/main/java/com/example/emptySaver/service/TimeTableService.java, src/main/java/com/example/emptySaver/utils/UosDepartmentAutoSaver.java, src/main/java/com/example/emptySaver/utils/UosSubjectAutoSaver.java, src/test/java/com/example/emptySaver/repository/SubjectRepositoryTest.java, src/test/java/com/example/emptySaver/service/SubjectServiceTest.java, src/test/java/com/example/emptySaver/service/TimeTableServiceTest.java
feat: change periodicType to String
=> Table dev - feat: change periodicType to String

src/test/java/com/example/emptySaver/service/SubjectServiceTest.java
=> fix: test build bug

src/main/java/com/example/emptySaver/controller/SubjectController.java, src/main/java/com/example/emptySaver/domain/dto/SubjectDto.java, src/main/java/com/example/emptySaver/domain/dto/TimeTableDto.java, src/main/java/com/example/emptySaver/domain/entity/Subject.java, src/main/java/com/example/emptySaver/repository/SubjectRepository.java, src/main/java/com/example/emptySaver/service/SubjectService.java, src/main/java/com/example/emptySaver/service/TimeTableService.java, src/test/java/com/example/emptySaver/service/SubjectServiceTest.java, src/test/java/com/example/emptySaver/service/TimeTableServiceTest.java
change ScheduleDto form to List<Boolean> timeData
=> Table dev: change ScheduleDto form

src/main/java/com/example/emptySaver/service/TimeTableService.java
-검색 시작일과 끝나는 일이 같으면 검색이 안되는 버그 수정
=> fix: timeTable search bug

src/main/java/com/example/emptySaver/domain/dto/TimeTableDto.java, src/main/java/com/example/emptySaver/domain/entity/Team.java, src/main/java/com/example/emptySaver/service/TimeTableService.java, src/test/java/com/example/emptySaver/service/TimeTableServiceTest.java
Team별 timeTable 추가 및 schedule return에 String time 정보 추가
=> feat: return time as String

src/main/java/com/example/emptySaver/utils/TimeDataToBitConverter.java, src/test/java/com/example/emptySaver/service/TimeTableServiceTest.java
=> fix: nonPeriodicSchedule to dto convert

src/main/java/com/example/emptySaver/controller/TimeTableController.java, src/main/java/com/example/emptySaver/domain/dto/GroupDto.java, src/main/java/com/example/emptySaver/service/GroupService.java
=> Table dev: group scheduleing

src/main/java/com/example/emptySaver/controller/FriendController.java, src/main/java/com/example/emptySaver/controller/GroupController.java, src/main/java/com/example/emptySaver/controller/TimeTableController.java
=> feat: load friends&GroupMember timeTable

src/main/java/com/example/emptySaver/controller/SubjectController.java, src/main/java/com/example/emptySaver/controller/TimeTableController.java, src/main/java/com/example/emptySaver/domain/dto/TimeTableDto.java, src/main/java/com/example/emptySaver/domain/entity/Schedule.java, src/main/java/com/example/emptySaver/domain/entity/Time_Table.java, src/main/java/com/example/emptySaver/repository/NonPeriodicScheduleRepository.java, src/main/java/com/example/emptySaver/repository/PeriodicScheduleRepository.java, src/main/java/com/example/emptySaver/repository/ScheduleRepository.java, src/main/java/com/example/emptySaver/service/TimeTableService.java, src/main/java/com/example/emptySaver/utils/TimeDataSuperUltraConverter.java, src/test/java/com/example/emptySaver/repository/ScheduleRepositoryTest.java, src/test/java/com/example/emptySaver/service/TimeTableServiceTest.java
=> Table dev: feat search schedule

src/main/java/com/example/emptySaver/controller/TimeTableController.java, src/main/java/com/example/emptySaver/domain/dto/TimeTableDto.java, src/main/java/com/example/emptySaver/service/TimeTableService.java, src/test/java/com/example/emptySaver/service/TimeTableServiceTest.java
member와 그 member의 그룹의 시간표도 모두 반환
=> Table dev feat :getMemberAndGroupTimeTable

src/main/java/com/example/emptySaver/controller/TimeTableController.java, src/main/java/com/example/emptySaver/domain/dto/TimeTableDto.java
=> feat: save member schedule to owner

src/main/java/com/example/emptySaver/controller/TimeTableController.java, src/main/java/com/example/emptySaver/domain/dto/TimeTableDto.java, src/main/java/com/example/emptySaver/repository/NonPeriodicScheduleRepository.java, src/main/java/com/example/emptySaver/service/ScheduleRecommendService.java, src/main/java/com/example/emptySaver/service/TimeTableService.java, src/main/java/com/example/emptySaver/service/impl/TimeTableServiceImpl.java, src/main/java/com/example/emptySaver/utils/TimeDataSuperUltraConverter.java, src/test/java/com/example/emptySaver/repository/ScheduleRepositoryTest.java, src/test/java/com/example/emptySaver/repository/SubjectRepositoryTest.java, src/test/java/com/example/emptySaver/service/ScheduleRecommendServiceTest.java
feat: recommentdSchedule by member timeTable
=> Table dev: recommentdSchedule

src/main/java/com/example/emptySaver/controller/TimeTableController.java, src/main/java/com/example/emptySaver/domain/entity/Time_Table.java, src/main/java/com/example/emptySaver/service/ScheduleRecommendService.java, src/main/java/com/example/emptySaver/service/impl/TimeTableServiceImpl.java, src/test/java/com/example/emptySaver/service/ScheduleRecommendServiceTest.java
=> Table dev feat: Group schedule time recommend

src/main/java/com/example/emptySaver/controller/TimeTableController.java
=> Table dev: feat group owner check

src/main/java/com/example/emptySaver/domain/dto/TimeTableDto.java, src/main/java/com/example/emptySaver/domain/entity/Schedule.java, src/main/java/com/example/emptySaver/service/impl/TimeTableServiceImpl.java
=> feat: add group data in scheduleDTO

src/main/java/com/example/emptySaver/controller/SubjectController.java, src/main/java/com/example/emptySaver/controller/TimeTableController.java, src/main/java/com/example/emptySaver/domain/dto/SubjectDto.java, src/main/java/com/example/emptySaver/domain/dto/TimeTableDto.java, src/main/java/com/example/emptySaver/domain/entity/Member.java, src/main/java/com/example/emptySaver/domain/entity/Schedule.java, src/main/java/com/example/emptySaver/domain/entity/Team.java, src/main/java/com/example/emptySaver/domain/entity/Time_Table.java, src/main/java/com/example/emptySaver/service/GroupService.java, src/main/java/com/example/emptySaver/service/MemberService.java, src/main/java/com/example/emptySaver/service/impl/TimeTableServiceImpl.java, src/test/java/com/example/emptySaver/repository/TimeTableRepositoryTest.java, src/test/java/com/example/emptySaver/service/ScheduleRecommendServiceTest.java, src/test/java/com/example/emptySaver/service/SubjectServiceTest.java, src/test/java/com/example/emptySaver/service/TimeTableServiceTest.java
=> Table dev feat: remove casecade apply

src/main/java/com/example/emptySaver/service/CrawlService.java
=> Table dev fix comment

src/main/java/com/example/emptySaver/controller/FriendController.java, src/main/java/com/example/emptySaver/controller/GroupController.java
=> chore: controller method

src/main/java/com/example/emptySaver/controller/TimeTableController.java, src/main/java/com/example/emptySaver/domain/entity/Schedule.java, src/main/java/com/example/emptySaver/repository/NonPeriodicScheduleRepository.java, src/main/java/com/example/emptySaver/service/CrawlService.java, src/main/java/com/example/emptySaver/service/ScheduleService.java
=> feat: Movie schedulization

src/main/java/com/example/emptySaver/controller/SubjectController.java, src/main/java/com/example/emptySaver/domain/dto/SubjectDto.java, src/main/java/com/example/emptySaver/service/SubjectService.java
=> Table dev: 부서 조회 기능

src/main/java/com/example/emptySaver/utils/ApiData.java, src/main/java/com/example/emptySaver/utils/UosSubjectAutoSaver.java
=> Table dev: 교양 강의 등록

src/main/java/com/example/emptySaver/utils/UosSubjectAutoSaver.java
=> Table dev: subject api url 오류 수정

src/main/java/com/example/emptySaver/utils/UosSubjectAutoSaver.java
=> fix: subject_div 오타 수정

src/main/java/com/example/emptySaver/utils/UosSubjectAutoSaver.java
=> feat: 교양 필수 등록

src/main/java/com/example/emptySaver/utils/UosSubjectAutoSaver.java
=> fix: add rotc 교직

src/main/java/com/example/emptySaver/utils/UosSubjectAutoSaver.java
=> chore: 오타수정

src/main/java/com/example/emptySaver/controller/TimeTableController.java, src/main/java/com/example/emptySaver/service/ScheduleRecommendService.java, src/main/java/com/example/emptySaver/service/impl/TimeTableServiceImpl.java
=> Table dev: 관심사로 추천 filtering

src/main/java/com/example/emptySaver/domain/dto/TimeTableDto.java, src/main/java/com/example/emptySaver/service/impl/TimeTableServiceImpl.java
=> Table dev: 스케줄 카테고리 설정

src/main/java/com/example/emptySaver/controller/TimeTableController.java, src/main/java/com/example/emptySaver/domain/entity/ScheduleMember.java, src/main/java/com/example/emptySaver/repository/ScheduleMemberRepository.java, src/main/java/com/example/emptySaver/service/TimeTableService.java, src/main/java/com/example/emptySaver/service/impl/TimeTableServiceImpl.java
스케줄 확인 시 list에서 제거 가능하도록 table에 기록
=> Table dev: 스케줄 확인 시 list에서 제거

src/main/java/com/example/emptySaver/domain/dto/TimeTableDto.java, src/main/java/com/example/emptySaver/domain/entity/Non_Periodic_Schedule.java, src/main/java/com/example/emptySaver/domain/entity/Periodic_Schedule.java, src/main/java/com/example/emptySaver/service/impl/TimeTableServiceImpl.java
=> Table dev: 스케줄 확인 여부 반환

src/main/java/com/example/emptySaver/domain/entity/Non_Periodic_Schedule.java, src/main/java/com/example/emptySaver/domain/entity/Periodic_Schedule.java, src/main/java/com/example/emptySaver/service/impl/TimeTableServiceImpl.java
=> Table dev: recommend 오류 수정

src/main/java/com/example/emptySaver/service/impl/TimeTableServiceImpl.java
=> null error fix

src/main/java/com/example/emptySaver/controller/TimeTableController.java
=> fix: readSchedule error

src/main/java/com/example/emptySaver/domain/entity/Schedule.java, src/main/java/com/example/emptySaver/domain/entity/ScheduleMember.java
=> fix: column 명 변경

src/main/java/com/example/emptySaver/controller/TimeTableController.java, src/main/java/com/example/emptySaver/service/ScheduleService.java, src/main/java/com/example/emptySaver/service/TimeTableService.java, src/main/java/com/example/emptySaver/service/impl/TimeTableServiceImpl.java
=> Table dev: save copy schedule 버그 수정

src/main/java/com/example/emptySaver/controller/TimeTableController.java, src/main/java/com/example/emptySaver/domain/dto/TimeTableDto.java, src/main/java/com/example/emptySaver/domain/entity/Non_Periodic_Schedule.java, src/main/java/com/example/emptySaver/domain/entity/Periodic_Schedule.java, src/main/java/com/example/emptySaver/domain/entity/Schedule.java, src/main/java/com/example/emptySaver/service/CategoryService.java, src/main/java/com/example/emptySaver/service/ScheduleRecommendService.java, src/main/java/com/example/emptySaver/service/ScheduleService.java, src/main/java/com/example/emptySaver/service/impl/TimeTableServiceImpl.java, src/main/java/com/example/emptySaver/utils/TimeDataSuperUltraConverter.java
팀 스케줄 카테고리 default 값 추가, 시간 response format 변경
=> Table dev: 팀 스케줄 카테고리 default 값 추가

src/main/java/com/example/emptySaver/controller/TimeTableController.java, src/main/java/com/example/emptySaver/service/ScheduleService.java, src/main/java/com/example/emptySaver/service/impl/TimeTableServiceImpl.java
스케줄 검색 오류 수정
스케줄 id로 복사본 저장하는 controller 구현
=> Table dev:  스케줄 검색 오류 수정

src/main/java/com/example/emptySaver/controller/TimeTableController.java, src/main/java/com/example/emptySaver/errorHandler/BaseResponseStatus.java, src/main/java/com/example/emptySaver/repository/NonPeriodicScheduleRepository.java, src/main/java/com/example/emptySaver/service/CrawlService.java, src/main/java/com/example/emptySaver/service/ScheduleService.java, src/main/java/com/example/emptySaver/service/impl/TimeTableServiceImpl.java
null pointer 오류 수정, 스케줄 form 검사
=> Table dev: null pointer 오류 수정, 스케줄 form 검사

src/main/java/com/example/emptySaver/controller/FriendController.java, src/main/java/com/example/emptySaver/controller/TimeTableController.java, src/main/java/com/example/emptySaver/domain/dto/FriendDto.java, src/main/java/com/example/emptySaver/domain/dto/TimeTableDto.java, src/main/java/com/example/emptySaver/domain/entity/Time_Table.java, src/main/java/com/example/emptySaver/service/FriendService.java, src/main/java/com/example/emptySaver/service/ScheduleRecommendService.java, src/main/java/com/example/emptySaver/service/impl/TimeTableServiceImpl.java
친구와 빈 시간 찾기, 설정한 빈 시간이 있는 친구 찾기
=> Table dev: 친구 시간표 정보를 이용한 기능 추가

src/main/java/com/example/emptySaver/controller/TimeTableController.java, src/main/java/com/example/emptySaver/domain/dto/TimeTableDto.java, src/main/java/com/example/emptySaver/service/CategoryService.java, src/main/java/com/example/emptySaver/service/CrawlService.java, src/main/java/com/example/emptySaver/service/ScheduleService.java, src/main/java/com/example/emptySaver/service/impl/TimeTableServiceImpl.java, src/test/java/com/example/emptySaver/service/TimeTableServiceTest.java
=> Table dev: 스케줄 valid 버그 수정

src/main/java/com/example/emptySaver/controller/TimeTableController.java, src/main/java/com/example/emptySaver/service/ScheduleService.java, src/main/java/com/example/emptySaver/service/TimeTableService.java, src/main/java/com/example/emptySaver/service/impl/TimeTableServiceImpl.java, src/test/java/com/example/emptySaver/service/TimeTableServiceTest.java
=> feat: update -> delete and save schedule

src/main/java/com/example/emptySaver/controller/TimeTableController.java, src/main/java/com/example/emptySaver/domain/entity/Non_Periodic_Schedule.java, src/main/java/com/example/emptySaver/domain/entity/Time_Table.java, src/main/java/com/example/emptySaver/errorHandler/BaseResponseStatus.java, src/main/java/com/example/emptySaver/service/ScheduleRecommendService.java, src/main/java/com/example/emptySaver/service/ScheduleService.java, src/main/java/com/example/emptySaver/service/impl/TimeTableServiceImpl.java, src/main/java/com/example/emptySaver/utils/TimeDataSuperUltraConverter.java, src/test/java/com/example/emptySaver/service/ScheduleRecommendServiceTest.java
=> Table dev: 스케줄 저장 전 overlap 검사

src/main/java/com/example/emptySaver/controller/FriendController.java, src/main/java/com/example/emptySaver/controller/GroupController.java, src/main/java/com/example/emptySaver/controller/TimeTableController.java, src/main/java/com/example/emptySaver/domain/dto/TimeTableDto.java, src/main/java/com/example/emptySaver/domain/entity/Non_Periodic_Schedule.java, src/main/java/com/example/emptySaver/domain/entity/Periodic_Schedule.java, src/main/java/com/example/emptySaver/domain/entity/Schedule.java, src/main/java/com/example/emptySaver/domain/entity/Time_Table.java, src/main/java/com/example/emptySaver/service/ScheduleRecommendService.java, src/main/java/com/example/emptySaver/service/TimeTableService.java, src/main/java/com/example/emptySaver/service/impl/TimeTableServiceImpl.java, src/test/java/com/example/emptySaver/service/SubjectServiceTest.java, src/test/java/com/example/emptySaver/service/TimeTableServiceTest.java
=> Table dev: 스케줄 숨기기 추가

src/main/java/com/example/emptySaver/service/impl/TimeTableServiceImpl.java, src/main/java/com/example/emptySaver/utils/UosSubjectAutoSaver.java
=> Table dev: 팀 스케줄 반환 기한 설정
